name: huahin
favicon: null
layout_spectrum: 0.88508
typography_spectrum: 0.33273
title: Hua Hin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0091c0'
    - '#fffffd'
    - '#958a6e'
    - '#ccc8ab'
    - '#cc0000'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
