name: huahin
favicon: null
layout_spectrum: 0.6091557960025966
typography_spectrum: 0.0018266921397298574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9063991601578891
  lightness: 0.16404252056963742
  saturation: 0.7460062534082681
  rhythmicContrast: 0.4647463003639132
purpose: []
